duet:
  ip_address: 192.168.1.2

CAMERA_PI:
  ip_address: 192.168.1.4
  port: 5000
  url_videoendpoint: video_feed
  url_stillendpoint: picture


DECK:
  sample_plates: [3,4] # which plates are specified as sample locations


DISPENSE_TOOL:
  pippette_0_offsets: (0,0)
  pippette_1_offsets: (10.0, -17.4)
  pippette_2_offsets: (-10.0, -17.4)

BAYESIAN_OPTIMIZATION:
